version: '3.8'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      - ../secrets/ssl:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
