version: '3.8'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    volumes:
      - ../secrets/ssl:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: on-failure;
      #    depends-on: wordpress
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: ./Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ..
      MYSQL_DATABASE: ..
      MYSQL_USER: ...
      MYSQL_PASSWORD: ...
    ports:
      - "3306:3306"
    volumes:
      - /home/aggrigor/data:/var/lib/mysql
    restart: on-failure
