version: '3.8'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    secrets:
      - nginx-cert
      - nginx-cert-key
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    restart: on-failure
      #    depends-on: wordpress
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: ./Dockerfile
    container_name: mariadb
    secrets:
      - db-root-password
      - db-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
      MYSQL_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: ..
      MYSQL_USER: ...
    ports:
      - "3306:3306"
    volumes:
      - /home/aggrigor/data:/var/lib/mysql
    restart: on-failure

secrets:
  nginx-cert:
    file: ../secrets/ssl/nginx.crt
  nginx-cert-key:
    file: ../secrets/ssl/nginx.key
  db-root-password:
    file: ../secrets/db_root_password.txt
  db-password:
    file: ../secrets/db_password.txt
