version: '3.8'

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    secrets:
      - nginx-cert
      - nginx-cert-key
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    networks:
      - my_network
    restart: on-failure
      #    depends-on: wordpress
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: ./Dockerfile
    container_name: mariadb
    secrets:
      - db-root-password
      - db-password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: ${MYSQL_ROOT_PASSWORD_FILE}
      MYSQL_PASSWORD_FILE: ${MYSQL_PASSWORD_FILE}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - /home/aggrigor/data:/var/lib/mysql
    networks:
      - my_network
    restart: on-failure

  adminer:
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - mariadb

networks:
  my_network:

secrets:
  nginx-cert:
    file: ../secrets/ssl/nginx.crt
  nginx-cert-key:
    file: ../secrets/ssl/nginx.key
  db-root-password:
    file: ../secrets/db_root_password.txt
  db-password:
    file: ../secrets/db_password.txt
